vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        submissions:
            upload_destination: default.storage # Use the name you defined for your storage here
            # https://foothills-forum.s3.us-east-2.amazonaws.com/girls-bb-p5-65d1f6ddbaac6138625715.jpg
            uri_prefix: https://%env(AWS_S3_BUCKET_NAME)%.s3.us-east-2.amazonaws.com
#            upload_destination: '%kernel.project_dir%/public/images/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

