vich_uploader:
    db_driver: orm

    mappings:
        submissions:
            uri_prefix: /images/submissions
            upload_destination: '%kernel.project_dir%/public/images/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
