vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        submissions:
            upload_destination: local_filesystem # default.storage # Use the name you defined for your storage here
            uri_prefix: /images/submissions
#            upload_destination: '%kernel.project_dir%/public/images/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

